FEATURES = [
  { name: 'Sports' },
  { name: 'Techie' },
  { name: 'Fashionista' },
  { name: 'Foodie' },
  { name: 'Outgoing' },
  { name: 'Male' },
  { name: 'Female' },
  { name: 'Friend' },
  { name: 'Family' },
  { name: 'Partner' },
  { name: 'Coworker' },
  { name: 'Acquaintance' },
  { name: 'Kid' },
  { name: 'Teen' },
  { name: 'Young adult' },
  { name: 'Adult' },
  { name: 'Elderly' },
  { name: 'Birthday' },
  { name: 'Party' },
  { name: 'Wedding' },
  { name: 'Graduation' },
  { name: 'Babyshower' },
  { name: 'Christmas' },
  { name: 'Officeparty' },
  { name: 'Anniversary' },
  { name: 'Housewarming' },
  { name: 'Practicality' },
]

GIFTS = [
  { name: 'Chocolate', description: 'sweet natural chocolate', price: 10, image: "chocolats", sku: "chocolate_01" },
  { name: 'Headphones', description: 'beats by Dre', price: 100, image: "headphones", sku: "headphones_01" },
  { name: 'Scarf', description: 'gucci pretty', price: 80, image:"scarf", sku: "scarf_01" },
  { name: 'Running shoes', description: 'dope nikerush', price: 100, image: "running_shoes1", sku: "nike_shoe_01" },
  { name: 'Wine', description: 'Menage a 3', price: 20, image:"levinrouge", sku: "wine_01" },
  { name: 'Sports tickets', description:'tickets for hockey or basketball or soccer', price: 100, image:"ticket", sku: "ticket_01" },
  { name: 'Ps4 wireless controller', description:'play forever', price: 60, image:"starwars_toy", image:"wireless_controller", sku: "ps4_wireless_01" },
  { name: 'Winter gloves', description: 'Windproof Polyester, Insulate Thinsulate, Waterproof', price: 40, image:"ganghiver", sku: "gloves_01" },
  { name: 'Beanie', description: 'Hand wash only, do not bleach', price: 20, image:"beanie1", sku: "beanie_01" },
  { name: 'Mug', description: 'keep your water, beer, or favorite drink on lock', price: 30, image:"mug", sku: "mug_01" },
  { name: 'Fitness watch', description: 'Heart Rate Monitor, Waterproof Smart Fitness,Step Counter, Calorie Counter', price: 50, image:"thewatchcalorie", sku: "fitness_watch_01" },
  { name: 'Yoga set kit', description: 'perform movements comfortably on the best mat', price: 80, image: "yogear", sku: "yoga_kit_01" },
  { name: 'Socks', description: 'Soft, comfortable, breathable, wearable, odor fighting', price: 20, image:"chaussettes", sku: "socks_01" },
  { name: 'Star wars toy', description: 'create adventures and scenes from Star Wars entertainment', price: 60, image:"bbtoy", sku: "starwars_toy_01" },
  { name: 'Doll', description: 'let young imaginations be the doctor with Barbie dolls and medical play sets', price: 40, image:"girlybarby", sku: "doll_01" },
  { name: 'Books', description: 'best selling autor', price: 30, image:"lelivre", sku: "book_01" },
  { name: 'Duffle bag', description:'inside zip-enclosed pocket heavy duty zippers  clips', price: 60, image:"lesac", sku: "bag_01" },
  { name: 'Amazing necklace', description: 'white and silver make today amazing necklace', price: 15, image: "necklace", sku: "necklace_01" },
  { name: 'Leather wallet', description: " Men's Leather Wallet", price: 25, image: "wallet", sku: "wallet_01" },
  { name: 'Tech and travel gear kit', description: 'Effortlessly carry and organize your tech and travel gear with The Everyday Dopp', price: 30, image:"tech_kit", sku: "travel_kit_01" },
  { name: 'Purple earrings', description: 'pair of purple earrings', price: 20, image: "earings", sku: "earings_01" },
  { name: 'Brushes', description: "women's face brushes", price: 20, image:"brushes", sku: "brushes_01" },
  { name: 'Throw pillow', description:'gray, yellow, and black throw pillow on gray suede couch', price: 14, image:"pillow", sku: "pillow_01" },
  { name: 'Camera vintage', description:'black and gray film camera', price: 50, image:"canon_camera", sku: "camera_vintage_01" },
  { name: 'Timberland shoes', description: 'Timberland Teddy Fleece Waterproof ', price: 140, image:"women_shoes", sku: "shoes_01" },
  { name: 'Wind chimes', description: 'Outdoor Living Wind Chimes Yard Garden Tubes Bells Copper Home Craft Decor Gifts', price: 10, image: "wind_chimes", sku: "wind_chime_01"},
  { name: 'Art glass', description: 'Purple Yellow Flower Art Glass Bird Bath Feeder NEW garden centerpiece bowl', price: 75, image: "birdbath", sku: "birdbath_01"},
  { name: 'Hammock', description: 'Sunnydaze 2-Person Quilted Spreader Bar Hammock and 12-Foot Stand - Melon Stripe', price: 150, image:"hammock", sku: "hammock_01"},
  { name: 'Bamboo MUG', description: 'STAINLESS STEEL Coffee & Tea Present,Travel', price: 30, image: "mugbamboo", sku: "mug_02"},
  { name: 'Christmas Bowl', description: 'Non-alcoholic yet full flavored red wine Fermented and aged in the traditional red wine method Alcohol is gently removed ', price: 20, image:"glass", sku: "bowl_01" },
  { name: 'Shallow Bowl', description:'Intricately woven antique gold-tone a beautifully striking addition to your tabletop. ', price: 160, image:"Shallow_Bowl", sku: "bowl_02"},
  { name: 'Canon Camera', description:'Canon EOS 200D 24.2 MP Digital SLR Camera with 18-55mm EF-S f/3.5-5.6 Lens ', price: 60, image:"cannon", sku: "camera_02"},
  { name: 'Echo Smart Speaker (2nd Generation)', description:'Canon EOS 200D 24.2 MP Digital SLR Camera with 18-55mm EF-S f/3.5-5.6 Lens ', price: 60, image:"cannon", sku: "camera_02"},

  { name: 'Tree Seed Starter Kit', description:'Grow 4 Bonsais From Seeds. Complete Bonzai Gardening Set W/ Organic Soil Mix, Biodegradable Planting Pots, Plant Labels & Guide', price: 33, image:"", sku: "tree_kit_01" },
  { name: 'Food Bucket List', description: 'Journal Foodie, Amus-Bouche, Small Plates Tapa, Gift for a Top Chef Recipes, and Meals', price: 25, image:"", sku: "bucket_01" },
  { name: 'Foot hammock', description: 'This must be a dream. Barefoot … in a hammock … at work. Does it get any cooler than this? Who says relaxation and hard work can’t go hand in hand?', price: 30, image: "", sku: "foot_hummock_01"},
  { name: 'The Walk By Scrabble Board', description: 'Show them who’s boss…but not too obviously, of course. Wreak passive-aggressive havoc with this walk-by game board.', price: 20, image: "", sku: "scrabble_01"},
  { name: 'Lego coffee mug', description: 'Everyone gets their best ideas when in the throes of a caffeine rush, but the tools aren’t always handy just then to construct their timeless masterpiece. ', price: 20, image:"", sku: "legomug_01"},
  { name: 'Guzzle buddy wine glass', description: 'Anyone who tells you that you can’t look classy drinking straight out of the bottle simply lacks imagination. And they clearly haven’t seen one of these. ', price: 20, image: "", sku: "glass_01"},
  { name: 'The subtle art of not Giving a fuck', description: 'Mark Manson seriously doesn’t give a f*ck, and he wants you to not give a f*ck too. Despite its (not so subtle) title, this book isn’t about not caring. It’s about not caring about the things that don’t matter', price: 20, image:"", sku: "book_01" },
  { name: 'Never have I ever game', description:'Help them learn more about the people around them than they could ever possibly want to know with the classic party game Never Have I Ever.', price: 25, image:"", sku: "cards_02"},
  { name: 'Bring me wine socks', description:'Generally speaking, the last person in the room who needs more wine is the person who’s already gone feet up.', price: 10, image:"", sku: "beersocks_02"},
]

