ATTRIBUTES = [
  { name: 'Sports' },
  { name: 'Techie' },
  { name: 'Fashionista' },
  { name: 'Foodie' },
  { name: 'Outgoing person' },
  { name: 'Male' },
  { name: 'Female' },
  { name: 'Other' },
  { name: 'Friend' },
  { name: 'Boss' },
  { name: 'Colleague' },
  { name: 'Family' },
  { name: 'Kid' },
  { name: 'Teen' },
  { name: 'Young adult' },
  { name: 'Adult' },
  { name: 'Elderly' },
  { name: 'Birthday' },
  { name: 'Party' },
  { name: 'Wedding' },
  { name: 'Graduation' },
  { name: 'Babyshower' },
  { name: 'Christmas' },
  { name: 'Office party' }
]

GIFTS = [
  {name: 'chocolate', description: 'sweet natural chocolate', price: 10, image: "chocolats"},
  {name: 'headphones', description: 'beats by Dre', price: 100, image: "headphones"},
  {name: 'scarf', description: 'gucci pretty', price: 80, image:"scarf"},
  {name: 'running shoes', description: 'dope nikerush', price: 100, image: "nike_shoe"},
  {name: 'wine', description: 'Menage a 3', price: 20, image:"levinrouge" },
  {name: 'sports tickets', description:'tickets for hockey or basketball or soccer', price: 100, image:"ticket"},
  {name: 'ps4 wireless controller', description:'play forever', price: 60, image:"starwars_toy"},
  {name: 'winter gloves', description: 'Windproof Polyester, Insulate Thinsulate, Waterproof', price: 40, image:"ganghiver"},
  {name: 'beanie', description: 'Hand wash only, do not bleach', price: 20, image:"beanie1"},
  {name: 'mug', description: 'keep your water, beer, or favorite drink on lock', price: 30, image:"tassecool"},
  {name: 'fitness watch', description: 'Heart Rate Monitor, Waterproof Smart Fitness,Step Counter, Calorie Counter', price: 50, image:"thewatchcalorie"},
  {name: 'yoga set kit', description: 'perform movements comfortably on the best mat', price: 80, image: "yogear"},
  {name: 'socks', description: 'Soft, comfortable, breathable, wearable, odor fighting', price: 20, image:"chaussettes"},
  {name: 'starwars toy', description: 'create adventures and scenes from Star Wars entertainment', price: 60, image:"bbtoy"},
  {name: 'barbie doctor playset', description: 'let young imaginations be the doctor with Barbie dolls and medical play sets', price: 40, image:"girlybarby"},
  {name: 'books', description: 'best selling autor', price: 30, image:"lelivre"},
  {name: 'duffle bag', description:'inside zip-enclosed pocket heavy duty zippers  clips', price: 60, image:"lesac"},
]
