FEATURES = [
  { name: 'Sports' },
  { name: 'Techie' },
  { name: 'Fashionista' },
  { name: 'Foodie' },
  { name: 'Party animal' },
  { name: 'Couch potato' },
  { name: 'Male' },
  { name: 'Female' },
  { name: 'Friend' },
  { name: 'Family' },
  { name: 'Partner' },
  { name: 'Coworker' },
  { name: 'Acquaintance' }, # We also need acquaintance and partner
  { name: 'Kid' },
  { name: 'Teen' },
  { name: 'Young adult' },
  { name: 'Adult' },
  { name: 'Elderly' },
  { name: 'Birthday' },
  { name: 'Party' },
  { name: 'Wedding' },
  { name: 'Graduation' },
  { name: 'Baby Shower' },
  { name: 'Christmas' },
  { name: 'Office Party' },
  { name: 'Anniversary' },
  # Check to have complete list
]

GIFTS = [
  {name: 'chocolate', description: 'Belgian Extra Creamy Milk Chocolate', price: 10, image: "chocolats"},
  {name: 'headphones', description: 'HD 4.50 BTNC Bluetooth Active Noise Cancellation Headphone', price: 100, image: "headphones"},
  {name: 'scarf', description: 'Gap Womens Mix-Pattern Diamond Tassel Scarf New Fuchsia, One Size', price: 80, image:"scarf"},
  {name: 'running shoes', description: 'On Cloud All Black, Lightweight Running Shoe,', price: 100, image: "nike_shoe"},
  {name: 'wine', description: 'Non-alcoholic yet full flavored red wine Fermented and aged in the traditional red wine method Alcohol is gently removed ', price: 20, image:"levinrouge" },
  {name: 'sports tickets', description:'Tickets for sports events, hockey, basketball or soccer', price: 100, image:"ticket"},
  {name: 'ps4 wireless controller', description:'Why fumble with your keyboard and mouse! Play like a champ with this handy universal controller. ', price: 60, image:"starwars_toy"},
  {name: 'winter gloves', description: 'Men Women Warm Waterproof Windproof Touch Screen Ski Cycling Gloves Full Finger Outdoor Fleece Glove', price: 40, image:"ganghiver"},
  {name: 'beanie', description: 'Black New Era Edition Logo Beanie. Hand wash only, do not bleach', price: 20, image:"beanie1"},
  {name: 'mug', description: 'Vintage Mugs - Cappuccino Mug', price: 30, image:"tassecool"},
  {name: 'fitness watch', description: 'Heart Rate Monitor, Waterproof Smart Fitness,Step Counter, Calorie Counter', price: 50, image:"thewatchcalorie"},
  {name: 'yoga pants', description: 'Flat-lock seams help prevent chafing. Soft, breathable jersey with four-way super stretch for ultimate movement. ', price: 80, image: "yogear"},
  {name: 'socks', description: 'Soft, comfortable, breathable, wearable, odor fighting', price: 20, image:"chaussettes"},
  {name: 'star wars toy', description: 'Star Wars Action & Toy Figures SW GH Power Up Multi Pack Playset', price: 60, image:"bbtoy"},
  {name: 'doll', description: 'let young imaginations be the guide with this doll', price: 40, image:"girlybarby"},
  {name: 'books', description: 'The Beautiful Poetry of Donald Trump', price: 30, image:"lelivre"},
  {name: 'duffle bag', description:'Stay organized and look smart. This functional duffel has a spot for everything you need.', price: 60, image:"lesac"},
  {name: 'Wind Chimes', description: 'Outdoor Living Wind Chimes Yard Garden Tubes Bells Copper Home Craft Decor Gifts', price: 10, image: ""},
  {name: 'Art Glass', description: 'Purple Yellow Flower Art Glass Bird Bath Feeder NEW garden centerpiece bowl', price: 75, image: "birdbath"},
  {name: 'Hammock', description: 'Sunnydaze 2-Person Quilted Spreader Bar Hammock and 12-Foot Stand - Melon Stripe', price: 150, image:"hammock"},
  {name: 'Bamboo MUG', description: 'STAINLESS STEEL Coffee & Tea Present,Travel', price: 30, image: "mugbamboo"},
  {name: 'Christmas Bowl', description: 'Non-alcoholic yet full flavored red wine Fermented and aged in the traditional red wine method Alcohol is gently removed ', price: 20, image:"glass" },
  {name: 'Shallow Bowl', description:'Intricately woven antique gold-tone a beautifully striking addition to your tabletop. ', price: 160, image:"Shallow_Bowl"},
  {name: 'Canon Camera', description:'Canon EOS 200D 24.2 MP Digital SLR Camera with 18-55mm EF-S f/3.5-5.6 Lens ', price: 60, image:"cannon"},
]