FEATURES = [
  { name: 'Sports' },
  { name: 'Techie' },
  { name: 'Fashionista' },
  { name: 'Foodie' },
  { name: 'Outgoing' },
  { name: 'Male' },
  { name: 'Female' },
  { name: 'Friend' },
  { name: 'Family' },
  { name: 'Partner' },
  { name: 'Coworker' },
  { name: 'Acquaintance' },
  { name: 'Kid' },
  { name: 'Teen' },
  { name: 'Young adult' },
  { name: 'Adult' },
  { name: 'Elderly' },
  { name: 'Birthday' },
  { name: 'Party' },
  { name: 'Wedding' },
  { name: 'Graduation' },
  { name: 'Babyshower' },
  { name: 'Christmas' },
  { name: 'Officeparty' },
  { name: 'Anniversary' },
  { name: 'Housewarming' },
  { name: 'Practicality' },
  # Check to have complete list
]

GIFTS = [
  { name: 'Chocolate', description: 'sweet natural chocolate', price: 10, image: "chocolats" },
  { name: 'Headphones', description: 'beats by Dre', price: 100, image: "headphones" },
  { name: 'Scarf', description: 'gucci pretty', price: 80, image:"scarf" },
  { name: 'Running shoes', description: 'dope nikerush', price: 100, image: "nike_shoe" },
  { name: 'Wine', description: 'Menage a 3', price: 20, image:"levinrouge" },
  { name: 'Sports tickets', description:'tickets for hockey or basketball or soccer', price: 100, image:"ticket" },
  { name: 'Ps4 wireless controller', description:'play forever', price: 60, image:"starwars_toy" },
  { name: 'Winter gloves', description: 'Windproof Polyester, Insulate Thinsulate, Waterproof', price: 40, image:"ganghiver" },
  { name: 'Beanie', description: 'Hand wash only, do not bleach', price: 20, image:"beanie1" },
  { name: 'Mug', description: 'keep your water, beer, or favorite drink on lock', price: 30, image:"tassecool" },
  { name: 'Fitness watch', description: 'Heart Rate Monitor, Waterproof Smart Fitness,Step Counter, Calorie Counter', price: 50, image:"thewatchcalorie" },
  { name: 'Yoga set kit', description: 'perform movements comfortably on the best mat', price: 80, image: "yogear" },
  { name: 'Socks', description: 'Soft, comfortable, breathable, wearable, odor fighting', price: 20, image:"chaussettes" },
  { name: 'Star wars toy', description: 'create adventures and scenes from Star Wars entertainment', price: 60, image:"bbtoy" },
  { name: 'Doll', description: 'let young imaginations be the doctor with Barbie dolls and medical play sets', price: 40, image:"girlybarby" },
  { name: 'Books', description: 'best selling autor', price: 30, image:"lelivre" },
  { name: 'Duffle bag', description:'inside zip-enclosed pocket heavy duty zippers  clips', price: 60, image:"lesac" },
  { name: 'Amazing necklace', description: 'white and silver make today amazing necklace', price: 15, image: "necklace" },
  { name: 'Leather wallet', description: " Men's Leather Wallet", price: 25, image: "wallet" },
  { name: 'Tech and travel gear kit', description: 'Effortlessly carry and organize your tech and travel gear with The Everyday Dopp', price: 30, image:"tech_kit" },
  { name: 'Purple earrings', description: 'pair of purple earrings', price: 20, image: "earings" },
  { name: 'Brushes', description: "women's face brushes", price: 20, image:"brushes" },
  { name: 'Throw pillow', description:'gray, yellow, and black throw pillow on gray suede couch', price: 14, image:"pillow" },
  { name: 'Camera vintage', description:'black and gray film camera', price: 50, image:"canon_camera" },
  { name: 'Timberland shoes', description: 'Timberland Teddy Fleece Waterproof ', price: 140, image:"women_shoes" },
  {name: 'Wind Chimes', description: 'Outdoor Living Wind Chimes Yard Garden Tubes Bells Copper Home Craft Decor Gifts', price: 10, image: ""},
  {name: 'Art Glass', description: 'Purple Yellow Flower Art Glass Bird Bath Feeder NEW garden centerpiece bowl', price: 75, image: "birdbath"},
  {name: 'Hammock', description: 'Sunnydaze 2-Person Quilted Spreader Bar Hammock and 12-Foot Stand - Melon Stripe', price: 150, image:"hammock"},
  {name: 'Bamboo MUG', description: 'STAINLESS STEEL Coffee & Tea Present,Travel', price: 30, image: "mugbamboo"},
  {name: 'Christmas Bowl', description: 'Non-alcoholic yet full flavored red wine Fermented and aged in the traditional red wine method Alcohol is gently removed ', price: 20, image:"glass" },
  {name: 'Shallow Bowl', description:'Intricately woven antique gold-tone a beautifully striking addition to your tabletop. ', price: 160, image:"Shallow_Bowl"},
  {name: 'Canon Camera', description:'Canon EOS 200D 24.2 MP Digital SLR Camera with 18-55mm EF-S f/3.5-5.6 Lens ', price: 60, image:"cannon"},
]

