meta_product_name: "Regalo"
meta_title: "Regalo - Find the perfect gift in minutes"
meta_description: "Rose will help you find the perfect gift for your next event, in minutes."
meta_image: "regalo-background_v2.jpg"
twitter_account: ""
