meta_product_name: "Regalo"
meta_title: "Regalo - Find the right gift"
meta_description: "Rose will help you find the right gift for your next event, in minutes"
meta_image: "regalo-background.jpg"
twitter_account: ""
